apiVersion: getambassador.io/v3alpha1
kind: AuthService
metadata:
  name: authentication
spec:
  auth_service: "http:simpleauth.demo:3333"
  path_prefix: "/bfauth"
  allowed_request_headers:
  - "x-myheader"
  allowed_authorization_headers:
  - "set-cookie"
